backend:
  name: git-gateway
  branch: netlify # Branch to update (optional; defaults to master)


# backend:
#   name: github
#   repo: cinetimes/cinetimes-fr # Path to your Github repository
#   branch: netlify



publish_mode: editorial_workflow
media_folder: "themes/cinetime/source/img/cover" # Media files will be stored in the repo under images/uploads
# public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Films" # Used in the UI
    folder: "/source/_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Titre Original", name: "original_title", widget: "string"}
      - {label: "Réalisateur", name: "author", widget: "string"}
      - {label: "Date de sortie", name: "release_date", widget: "date", format: "MMM Do YY"}
      - {label: "Synopsis", name: "synopsis", widget: "text"}
      - {label: "Image de Couverture", name: "img_path", widget: "image"}
      - {label: "Note de 1 à 10", name: "rating", widget: "number", min: "0", max: "10", valueType: "float"}
      - label: "Categorie"
        name: "category"
        widget: "select"
        options: ["Films", "Dessins Animés", "Documentaires"]
      - label: "Genre"
        name: "tags"
        widget: "list"
        default: ["Action", "Aventure", "Animation"]
      - {label: "Youtube", name: "youtube_url", widget: "string", required: false}
      - {label: "Vimeo", name: "vimeo_url", widget: "string", required: false}
      - {label: "Archive.org", name: "archive_url", widget: "string", required: false}
      - {label: "Dailymotion", name: "dailymotion_url", widget: "string", required: false}
      - {label: "Webtorrent (lien magnet)", name: "webtorrent_magnet", widget: "string", required: false}
      # - label: "Acteurs"
      #   name: "cast"
      #   widget: "list"
      #   default: ["Brad Pitt", "..."]
      - {label: "Acteurs", name: "cast", widget: "string", default: "Brad Pitt, ..."}
      # - label: "Équipe Technique"
      #   name: "crew"
      #   widget: "list"
      #   default: ["Charles Chaplin", "James Cameron", "..."]
      - {label: "Équipe Technique", name: "crew", widget: "string", default: "Charles Chaplin, James Cameron, ..."}
      - {label: "Description (optionnel)", name: "content", widget: "markdown", required: false}


  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "/source/_posts/blog/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de sortie", name: "release_date", widget: "datetime"}
      - {label: "Image de Couverture", name: "thumbnail", widget: "image"}
      - {label: "Fiche", name: "body", widget: "markdown"}


    #  - label: "Genres"
    #     name: "tags"
    #     widget: "list"
    #     fields:
    #       - label: "Genre"
    #         name: tags
    #         widget: "select"
    #         options: ["Action", "Aventure", "Comédie", "Comédie Dramatique", "Crime", "Drame", "Espionnage", "Épouvante-Horreur", "Fantastique", "Guerre", "Histoire", "Muet", "Policier", "Propagande", "Romance", "Science-Fiction", "Thriller", "Western", ]
 
      # - label: "Liens vers la vidéo"
      #   name: "videos"
      #   widget: "object"
      #   fields:
      #     - {label: "Youtube", name: "youtube_url", widget: "string"}
      #     - {label: "Vimeo", name: "vimeo_url", widget: "string"}
      #     - {label: "Archive.org", name: "archive_url", widget: "string"}
      #     - {label: "Dailymotion", name: "dailymotion_url", widget: "string"}
      #     - {label: "Webtorrent (lien magnet)", name: "webtorrent_magnet", widget: "string"}